--Games
INSERT INTO GAME_DETAILS VALUES(1, 'Dota 2', 'Steam');

INSERT INTO GAME_DETAILS VALUES(2, 'CS GO', 'Steam');

INSERT INTO GAME_DETAILS VALUES(3, 'PUBG', 'Steam');

INSERT INTO GAME_DETAILS VALUES(4, 'FIFA20', 'Origin');

INSERT INTO GAME_DETAILS VALUES(6, 'SIMS 4', 'Origin');

INSERT INTO GAME_DETAILS VALUES(7, 'Blackjack', 'Parimatch');

INSERT INTO GAME_DETAILS VALUES(8, 'Poker', 'Parimatch');

INSERT INTO GAME_DETAILS VALUES(9, 'Roulette', 'Parimatch');

INSERT INTO GAME_DETAILS VALUES(10, 'Texas holdem', 'Pokerstars');

INSERT INTO GAME_DETAILS VALUES(11, 'Casino', 'Pokerstars');



--Currencies
INSERT INTO CURRENCY VALUES (1, 'UAH');

INSERT INTO CURRENCY VALUES (2, 'USD');

INSERT INTO CURRENCY VALUES (3, 'EUR');

--Countries
INSERT INTO COUNTRY VALUES (1, 'UA');

INSERT INTO COUNTRY VALUES (2, 'PL');

INSERT INTO COUNTRY VALUES (3, 'GB');

INSERT INTO COUNTRY VALUES (4, 'USA');

--GAME_COUNTRY
--Game 1
INSERT INTO GAME_COUNTRY VALUES (1, 1);
INSERT INTO GAME_COUNTRY VALUES (1, 2);
INSERT INTO GAME_COUNTRY VALUES (1, 3);
INSERT INTO GAME_COUNTRY VALUES (1, 4);

--Game 2
INSERT INTO GAME_COUNTRY VALUES (2, 1);
INSERT INTO GAME_COUNTRY VALUES (2, 2);
INSERT INTO GAME_COUNTRY VALUES (2, 3);
INSERT INTO GAME_COUNTRY VALUES (2, 4);

--Game 3
INSERT INTO GAME_COUNTRY VALUES (3, 1);
INSERT INTO GAME_COUNTRY VALUES (3, 2);
INSERT INTO GAME_COUNTRY VALUES (3, 3);
INSERT INTO GAME_COUNTRY VALUES (3, 4);

--Game 4
INSERT INTO GAME_COUNTRY VALUES (4, 1);
INSERT INTO GAME_COUNTRY VALUES (4, 2);
INSERT INTO GAME_COUNTRY VALUES (4, 3);
INSERT INTO GAME_COUNTRY VALUES (4, 4);


--Game 6
INSERT INTO GAME_COUNTRY VALUES (6, 1);
INSERT INTO GAME_COUNTRY VALUES (6, 2);
INSERT INTO GAME_COUNTRY VALUES (6, 3);
INSERT INTO GAME_COUNTRY VALUES (6, 4);

--Game 7
INSERT INTO GAME_COUNTRY VALUES (7, 1);
INSERT INTO GAME_COUNTRY VALUES (7, 2);
INSERT INTO GAME_COUNTRY VALUES (7, 4);

--Game 8
INSERT INTO GAME_COUNTRY VALUES (8, 1);
INSERT INTO GAME_COUNTRY VALUES (8, 2);
INSERT INTO GAME_COUNTRY VALUES (8, 4);

--Game 9
INSERT INTO GAME_COUNTRY VALUES (9, 1);
INSERT INTO GAME_COUNTRY VALUES (9, 2);
INSERT INTO GAME_COUNTRY VALUES (9, 4);

--Game 10
INSERT INTO GAME_COUNTRY VALUES (10, 1);
INSERT INTO GAME_COUNTRY VALUES (10, 4);

--Game 11
INSERT INTO GAME_COUNTRY VALUES (11, 1);
INSERT INTO GAME_COUNTRY VALUES (11, 4);

--GAME_CURRENCY
--Game 1
INSERT INTO GAME_CURRENCY VALUES (1, 1);
INSERT INTO GAME_CURRENCY VALUES (1, 2);
INSERT INTO GAME_CURRENCY VALUES (1, 3);

--Game 2
INSERT INTO GAME_CURRENCY VALUES (2, 1);
INSERT INTO GAME_CURRENCY VALUES (2, 2);
INSERT INTO GAME_CURRENCY VALUES (2, 3);

--Game 3
INSERT INTO GAME_CURRENCY VALUES (3, 1);
INSERT INTO GAME_CURRENCY VALUES (3, 2);
INSERT INTO GAME_CURRENCY VALUES (3, 3);

--Game 4
INSERT INTO GAME_CURRENCY VALUES (4, 1);
INSERT INTO GAME_CURRENCY VALUES (4, 2);
INSERT INTO GAME_CURRENCY VALUES (4, 3);


--Game 6
INSERT INTO GAME_CURRENCY VALUES (6, 1);
INSERT INTO GAME_CURRENCY VALUES (6, 2);
INSERT INTO GAME_CURRENCY VALUES (6, 3);

--Game 7
INSERT INTO GAME_CURRENCY VALUES (7, 1);
INSERT INTO GAME_CURRENCY VALUES (7, 2);

--Game 8
INSERT INTO GAME_CURRENCY VALUES (7, 1);
INSERT INTO GAME_CURRENCY VALUES (7, 2);

--Game 9
INSERT INTO GAME_CURRENCY VALUES (7, 1);
INSERT INTO GAME_CURRENCY VALUES (7, 2);

--Game 10
INSERT INTO GAME_CURRENCY VALUES (7, 2);

--Game 11
INSERT INTO GAME_CURRENCY VALUES (7, 2);


